server.port=8080

# 阿里云云数据库配置
spring.datasource.url=jdbc:mysql://rm-cn-vt74sxwl40002b5o.rwlb.rds.aliyuncs.com:3306/nanchang_history?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=team_user
spring.datasource.password=TeamPass123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 配置连接池（推荐加上）
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
